name = "olofson"
description = "SDL2 demos"
version = "25.0.0"
licenses = "GPL-2.0-only"

long-description = """
SDL2 demos.
"""

tags = ["sdl2", "demo", "game"]

project-files = [
	      "parallax_3.gpr",
	      "parallax_4.gpr",
	      "ballfield.gpr",
	      "fixedrate.gpr"
	      ]
executables = [
	    "parallax3",
	    "parallax4",
	    "ballfield",
	    "fixedrate"
	    ]
authors = ["Olofson", "Jesper Quorning"]
maintainers = ["Jesper Quorning <jesper.quorning@gmail.com>"]
maintainers-logins = ["jquorning"]

[[depends-on]]
sdlada = "=2.5.20"
